name: instagram_clone
description: Instagram clone application with flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: '>=2.18.1 <3.0.0'

dependencies:
    cached_network_image: ^3.2.3
    carousel_slider: ^4.2.1
    chat_bubbles: ^1.4.1
    cloud_firestore: ^4.1.0
    connectivity_plus: ^4.0.1
    cupertino_icons: ^1.0.2
    dartz: ^0.10.1
    dio: ^5.2.0+1
    equatable: ^2.0.5
    firebase_app_check: ^0.1.1+5
    firebase_auth: ^4.1.3
    firebase_core: ^2.3.0
    firebase_messaging: ^14.2.2
    firebase_storage: ^11.0.6
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.1
    flutter_facebook_auth: ^5.0.6
    fluttertoast: ^8.0.9
    geocoding: ^2.0.5
    geolocator: ^9.0.2
    get_it: ^7.2.0
    google_maps_flutter: ^2.2.1
    hive: null
    hive_flutter: null
    html: ^0.15.1
    http: ^0.13.5
    image_picker: ^0.8.6
    path_provider: ^2.0.11
    photo_view: ^0.14.0
    shimmer: ^3.0.0
    url_launcher: ^6.1.8
    video_compress: ^3.1.1
    video_player: ^2.4.7

dev_dependencies:
    build_runner: null
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter
    hive_generator: null

flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - assets/icons/
    # fonts:
    #   - family: IconBroken
    #     fonts:
    #       - asset: assets/fonts/icons.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
